final fix hopefully

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -24,23 +24,28 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Install Azure CLI
+        if: ${{ github.event.inputs.action == 'build' }}
         uses: pietrobolcato/install-azure-cli-action@v1.0.1
 
       - name: Install necessary tools
+        if: ${{ github.event.inputs.action == 'build' }}
         run: |
           sudo apt-get update
           sudo apt-get install -y curl unzip wget apt-transport-https gnupg2 software-properties-common git ca-certificates
 
       - name: Install Terraform
+        if: ${{ github.event.inputs.action == 'build' }}
         uses: little-core-labs/install-terraform@v2.0.0
         with:
           version: 1.7.5
 
       - name: Install kubectl
+        if: ${{ github.event.inputs.action == 'build' }}
         run: |
           sudo snap install kubectl --classic
 
       - name: Install Helm
+        if: ${{ github.event.inputs.action == 'build' }}
         uses: Azure/setup-helm@v4
         with:
           version: v3.7.0
@@ -49,53 +54,48 @@ jobs:
           
 
       - name: Azure login
+        if: ${{ github.event.inputs.action == 'build' }}
         run: az login
 
       - name: Terraform setup and apply/destroy (infrastructure)
+        if: ${{ github.event.inputs.action == 'build' }}
         run: |
-          cd infrastructure && \
-          terraform init || { echo "Terraform initialization failed"; exit 1; } && \
-          terraform validate || { echo "Terraform validation failed"; exit 1; } && \
-          if [ "${{ github.event.inputs.action }}" = "build" ]; then
+          if [ -d "infrastructure" ]; then
+            cd infrastructure && \
+            terraform init || { echo "Terraform initialization failed"; exit 1; } && \
+            terraform validate || { echo "Terraform validation failed"; exit 1; } && \
             terraform plan -out=tfplan || { echo "Terraform planning failed"; exit 1; } && \
             terraform apply tfplan || { echo "Terraform apply failed"; exit 1; }
-          elif [ "${{ github.event.inputs.action }}" = "cleanup" ]; then
-            terraform destroy -auto-approve || { echo "Terraform destroy failed"; exit 1; }
+          else
+            echo "The 'infrastructure' directory does not exist."
+            exit 1
           fi
 
       - name: Wait for k8s cluster to be ready
+        if: ${{ github.event.inputs.action == 'build' }}
         run: sleep 60
 
       - name: Get AKS credentials
+        if: ${{ github.event.inputs.action == 'build' }}
         run: |
           az aks get-credentials --resource-group capstonerg --name capstoneaks
 
       - name: Terraform setup and apply/destroy (helm_charts)
+        if: ${{ github.event.inputs.action == 'build' }}
         run: |
-          cd helm_charts && \
-          terraform init || { echo "Terraform initialization failed"; exit 1; } && \
-          terraform validate || { echo "Terraform validation failed"; exit 1; } && \
-          if [ "${{ github.event.inputs.action }}" = "build" ]; then
+          if [ -d "helm_charts" ]; then
+            cd helm_charts && \
+            terraform init || { echo "Terraform initialization failed"; exit 1; } && \
+            terraform validate || { echo "Terraform validation failed"; exit 1; } && \
             terraform plan -out=tfplan || { echo "Terraform planning failed"; exit 1; } && \
             terraform apply tfplan || { echo "Terraform apply failed"; exit 1; }
-          elif [ "${{ github.event.inputs.action }}" = "cleanup" ]; then
-            terraform destroy -auto-approve || { echo "Terraform destroy failed"; exit 1; }
+          else
+            echo "The 'helm_charts' directory does not exist."
+            exit 1
           fi
 
-      - name: Extract subscriptionId
-        id: extract_sub
-        run: echo "::set-output name=subscription_id::$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.subscriptionId')"
-        shell: bash
-
-      - name: Get AKS credentials
-        id: get_credentials
-        uses: azure/aks-set-context@v1
-        with:
-            subscriptionId: ${{ steps.extract_sub.outputs.subscription_id }}
-            resource-group: capstonerg
-            cluster-name: capstoneaks
-
       - name: Apply microservices YAML
+        if: ${{ github.event.inputs.action == 'build' }}
         run: |
           cd microservices && \
           attempt=1 && \
@@ -110,6 +110,7 @@ jobs:
           done
 
       - name: Apply letsencrypt YAML
+        if: ${{ github.event.inputs.action == 'build' }}
         run: |
           cd letsencrypt && \
           attempt=1 && \
@@ -124,6 +125,7 @@ jobs:
           done
 
       - name: Apply argocd YAML
+        if: ${{ github.event.inputs.action == 'build' }}
         run: |
           cd argocd && \
           attempt=1 && \
@@ -138,6 +140,7 @@ jobs:
           done
 
       - name: Apply nginx-ingress YAML
+        if: ${{ github.event.inputs.action == 'build' }}
         run: |
           cd ingress && \
           attempt=1 && \
@@ -152,9 +155,11 @@ jobs:
           done
 
       - name: Wait for nginx-ingress to be ready
+        if: ${{ github.event.inputs.action == 'build' }}
         run: sleep 30
 
       - name: Apply sock-shop YAML in ingress directory
+        if: ${{ github.event.inputs.action == 'build' }}
         run: |
           cd ingress && \
           attempt=1 && \
@@ -169,9 +174,11 @@ jobs:
           done
 
       - name: Wait for 10 seconds before applying Prometheus Stack YAMLs
+        if: ${{ github.event.inputs.action == 'build' }}
         run: sleep 10
 
       - name: Apply Prometheus Stack CRDs
+        if: ${{ github.event.inputs.action == 'build' }}
         run: |
           cd prometheus_stack/crds && \
           attempt=1 && \
@@ -186,9 +193,11 @@ jobs:
           done
 
       - name: Wait for 10 seconds before applying Prometheus Operator YAMLs
+        if: ${{ github.event.inputs.action == 'build' }}
         run: sleep 10
 
       - name: Apply Prometheus Operator YAML
+        if: ${{ github.event.inputs.action == 'build' }}
         run: |
           cd prometheus_stack/prometheus-operator && \
           attempt=1 && \
@@ -203,9 +212,11 @@ jobs:
           done
 
       - name: Wait for 10 seconds before applying Prometheus YAMLs
+        if: ${{ github.event.inputs.action == 'build' }}
         run: sleep 10
 
       - name: Apply Prometheus YAML
+        if: ${{ github.event.inputs.action == 'build' }}
         run: |
           cd prometheus_stack/prometheus && \
           attempt=1 && \
@@ -220,9 +231,11 @@ jobs:
           done
 
       - name: Wait for 10 seconds before applying Grafana YAMLs
+        if: ${{ github.event.inputs.action == 'build' }}
         run: sleep 10
 
       - name: Apply Grafana YAML
+        if: ${{ github.event.inputs.action == 'build' }}
         run: |
           cd prometheus_stack/grafana && \
           attempt=1 && \
@@ -237,9 +250,11 @@ jobs:
           done
 
       - name: Wait for 10 seconds before applying Alert Manager YAMLs
+        if: ${{ github.event.inputs.action == 'build' }}
         run: sleep 10
 
       - name: Apply Alert Manager YAML
+        if: ${{ github.event.inputs.action == 'build' }}
         run: |
           cd prometheus_stack/alertmanager && \
           attempt=1 && \
@@ -254,14 +269,17 @@ jobs:
           done
 
       - name: Wait for 10 seconds before applying ELK Stack YAMLs
+        if: ${{ github.event.inputs.action == 'build' }}
         run: sleep 10
 
       - name: Apply namespace.yaml in elk_stack directory
+        if: ${{ github.event.inputs.action == 'build' }}
         run: |
           cd elk_stack && \
           kubectl apply -f namespace.yaml || kubectl apply -f namespace.yaml
 
       - name: Apply other YAML files in elk_stack directory
+        if: ${{ github.event.inputs.action == 'build' }}
         run: |
           cd elk_stack && \
           attempt=1 && \
@@ -274,3 +292,22 @@ jobs:
             sleep 10
             ((attempt++))
           done
+
+      - name: Clean up
+        if: ${{ github.event.inputs.action == 'cleanup' }}
+        run: |
+          if [ -d "helm_charts" ]; then
+            cd helm_charts && \
+            terraform destroy -auto-approve || { echo "Terraform destroy failed"; exit 1; }
+          else
+            echo "The 'helm_charts' directory does not exist."
+            exit 1
+          fi
+
+          if [ -d "infrastructure" ]; then
+            cd infrastructure && \
+            terraform destroy -auto-approve || { echo "Terraform destroy failed"; exit 1; }
+          else
+            echo "The 'infrastructure' directory does not exist."
+            exit 1
+          fi
